name: Utility Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install C build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Compile C code
        run: |
          gcc -o example ./clibs/example.h

      - name: Install Rust dependencies
        run: cargo build --release

      - name: Run benchmarks
        run: cargo bench
